pygments:       true
permalink:      /:categories/:title/
paginate:       5

exclude:
    - README.md

title:          МКП "ЖКХ"
url:            http://mkpjkh.github.com
feed:           /atom.xml
description:    "официальный сайт МКП ЖКХ г.Топки"
comment:        официальный сайт МКП ЖКХ г.Топки

author:
    name:       МКП ЖКХ

contact:
    name:       МКП "ЖКХ"
    address:	652300, РФ, Кемеровская обл., г. Топки, ул. Горная, д.17
    requisites:	ИНН4230005515,  КПП 423001001, ОГРН 1124230001048, р/с 40702810656080000165, к/с 30101810800000000782, Кемеровский РФ ОАО «Россельхозбанк» г. Кемерово
    email:      mkpjkh-topki@mail.ru
    phone: 	8 (384-54) 4-80-14
    
about: >
    т. 8 (384-54) 4-80-14
    
nav:
    - name:     Главная
      url:      /
    
    - name:     Тарифы
      url:      /tariffs/
    
    - name:     Контакты
      url:      /about/
      subnav:
        - name: email
          url:  mailto:mkpjkh-topki@mail.ru
         
copyright:
    - Создание сайта <a href="http://glaf.narod.ru">Александр Шелеметьев</a>
    - "&copy; Copyright 2013, Александр Шелеметьев. All Rights Reserved."
      
css:
    - /lib/appden.css
    - /lib/syntax.css
    
js:
    - http://ajax.googleapis.com/ajax/libs/mootools/1.2.4/mootools-yui-compressed.js
    - /lib/mootools-more.js
    - /lib/appden.js
