pygments:       true
permalink:      /:categories/:title/
paginate:       5

exclude:
    - README.md
    - Rakefile

title:          МКП ЖКХ г.Топки
url:            http://mkpjkh.github.com
feed:           /atom.xml
description:    "официальный сайт МКП ЖКХ г.Топки"
comment:        официальный сайт МКП ЖКХ г.Топки

author:
    name:       МКП ЖКХ г.Топки
    email:      mkpjkh-topki@mail.ru
    
about: >
    т. 8 (384-54) 4-80-14
    
nav:
    - name:     Главная
      url:      /
    
    - name:     Тарифы
      url:      /tariffs/
    
    - name:     Контакты
      url:      /about/
      subnav:
        - name: email
          url:  mailto:mkpjkh-topki@mail.ru
    
footer:
    - verb:     Thinking
      action:   How do people keep up with blogging?

      
copyright:
    - Создание сайта <a href="http://glf.narod.ru">Александр Шелеметьев</a>
    - "&copy; Copyright 2013, Александр Шелеметьев. All Rights Reserved."
      
css:
    - /lib/appden.css
    - /lib/syntax.css
    
js:
    - http://ajax.googleapis.com/ajax/libs/mootools/1.2.4/mootools-yui-compressed.js
    - /lib/mootools-more.js
    - /lib/appden.js

